# Generated by Django 3.2.4 on 2021-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0002_alter_workbook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
