# Generated by Django 3.2.4 on 2021-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0009_auto_20210707_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workbook',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
