# Generated by Django 3.2.4 on 2021-07-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0010_auto_20210714_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='chapter',
        ),
    ]
