# Generated by Django 3.2.4 on 2021-07-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0011_remove_page_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
    ]
