# Generated by Django 3.2.4 on 2021-07-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0013_question_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
