# Generated by Django 3.2.4 on 2021-07-23 15:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0015_auto_20210722_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='language',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
