# Generated by Django 3.2.4 on 2021-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0017_auto_20210723_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
