# Generated by Django 3.2.4 on 2021-08-06 16:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('workbooks', '0018_alter_workbook_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
