# Generated by Django 3.2.4 on 2021-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0019_workbook_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
