# Generated by Django 3.2.4 on 2021-08-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0020_workbook_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='back_matter',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='front_matter',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='workbook',
        ),
        migrations.AddField(
            model_name='chapter',
            name='workbook',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workbooks.workbook'),
            preserve_default=False,
        ),
    ]
