# Generated by Django 3.2.4 on 2021-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0021_auto_20210822_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='content',
            field=models.JSONField(blank=True),
        ),
    ]
